GET https://localhost:7041/dinners
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZDliM2Q1MS04ZjhhLTRkYWEtOTcwMy0wOTlkMTQ1MzcxY2IiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNmEwY2UyMzEtNzdhZi00ZjFiLTgxMTctY2QyM2IyZWRmZDI4IiwiZXhwIjoxNzU2NzkzMjc3LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.nZDfoQNgF5faVyO6jMWKzncaQga7Qw8itpaA7WuSyWU