GET https://localhost:7041/dinners
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NDFiOTg5MC1jMjA0LTRhYzgtOTA1Zi1hNjQwOTFjN2VkYmMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiOWU0NjlhNDYtMzg4YS00YWI5LWIwZWItMTQ3ZDlkN2RiZWYzIiwiZXhwIjoxNzU2NjQ3NjM4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.fED6SyvAdSfOxteeqttPcjtiRQId0VMAT9JMoi4CeqQ