@host=https://localhost:7041
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWMzNWMxNS0wZDY5LTQ1NDItOTcxMy0wODBmOTA4MDNlZDMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiYmIxODNlMDItMjJjYi00ODVlLTgzOWItOWZjNjQ4ZTFjNWJhIiwiZXhwIjoxNzU2ODEzNDIyLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.kKf5PQWkywEfR4slSTN5mHZLbJKWbf_BIygdOCcitKE
@hostId=asdsa
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Menu Name",
    "description": "Yammy Menu",
    "sections": [
        {
            "name": "Appetizers",
            "Description": "Appetizers",
            "items": [
                {
                    "name": "Hlwa",
                    "description": "Hlwa"
                }
            ]
        }
    ] 
}