@host=https://localhost:5001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjFkNDE0MC1jMDQyLTQ3YzMtODFhOS0yYzQ2ZjY5ODI5MzYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMGNjYjg4NTAtMmNlMS00MTkwLTk4YmQtZGIxZDI5YjYwNDQ3IiwiZXhwIjoxNzU2ODU1ODQ0LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.3Z-kjXlpkRjEcfvn_3SeCWDfan_hPZtuijezf-Q99EA
@hostId=asdsa
GET {{host}}/hosts/{{hostId}}/menus?pageNumber=1&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}